version: '3.8'

services:
  fastapi_server:
    image: phamducanh2k5/fb_batch_request_server:latest
    container_name: fastapi_server_8010
    environment:
      - LOG_DIR=/code/app/logs
    volumes:
      # Mount thư mục logs để app có thể ghi log
      - ./logs:/code/app/logs
      # Mount thư mục static để app phục vụ dashboard
      - ./static:/code/static
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8010/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:alpine
    container_name: nginx_8010
    ports:
      # Chỉ cần public một cổng duy nhất cho toàn bộ ứng dụng
      - "8010:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-net
    depends_on:
      fastapi_server:
        condition: service_healthy # Chờ FastAPI khỏe mạnh mới khởi động

networks:
  app-net:
    driver: bridge

# Không còn volume của elasticsearch nữa
volumes: {}