filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/fastapi/*.json # Lấy log từ thư mục này BÊN TRONG container
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"] # Gửi log đến Elasticsearch