# nginx/default.conf

server {
    # Nginx sẽ lắng nghe ở cổng 8000 bên trong container
    listen 8000;
    server_name localhost;

    # Logic bảo vệ cho dashboard và logs
    location ~ ^/(dashboard|logs|static) {
        auth_basic "Dashboard Access";
        auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
        
        proxy_pass http://fastapi_server:8004;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Các đường dẫn khác (ví dụ: /batch) sẽ không cần xác thực
    location / {
        proxy_pass http://fastapi_server:8004;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}